# BACKEND
backend = "egl";
vsync = true;
use-damage = true;
dithered-present = false;
# BLUR
blur: {
  method = "none";
};
blur-background = false;
# FADING
fading = true;
fade-in-step = 0.04;
fade-out-step = 0.04;
fade-delta = 4;

# LOGGING
log-level = "warn";

# RULES
rules = (
  { match = "focused"; opacity = 1; },
  { match = "!focused"; opacity = 0.89; },
  { match = "class_g = 'firefox'"; blur-background = false; },
  { match = "window_type = 'dock'"; blur-background = false; shadow = false; },
  { match = "window_type = 'desktop'"; blur-background = false; shadow = false; },
  { match = "tooltip"; fade = true; shadow = false; opacity = 0.9; focus = true; },
  { match = "popup_menu"; opacity = 0.85; },
  { match = "dropdown_menu"; opacity = 0.85; },
  { match = "class_g *?= 'slop'"; blur-background = false; opacity = 1; focus = true; },
  { match = "class_g *?= 'screenkey'"; blur-background = false; opacity = 1; focus = true; }
);
